### ISSUE TITLE
Remote shop interaction does not work with chat colors

### ISSUE THREAD

**Issue by hvtess** [BlvckBytes/QuickShopSearch#19]
When installed on a server with ChatColor players are unable to use the remote interaction feature.

Displays an error message in chat after typing a number:
"Your input does not resemble an integer greater than zero!"

Could color codes be ignored when processing shop requests?

**Comment by BlvckBytes** [comment]
How interesting! I totally forgot to account for this case, as chat-messages can obviously be auto-colored by other plugins; I'll make sure to get a new release out as soon as possible!

**Comment by BlvckBytes** [comment]
Please give the latest release a try - it should've solved your issue; if so, and if my work is of any help to you in general, starring the repository would help a bunch! ☺️

**Comment by hvtess** [comment]
> Please give the latest release a try - it should've solved your issue; if so, and if my work is of any help to you in general, starring the repository would help a bunch! ☺️

Issue has been fixed, thank you very much!
