### ISSUE TITLE
Some problems when using Tab Completion

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/QuickShopSearch#2]
Tab can also complete the second value after the first value has been entered.
![6de9a9a1-af0a-4980-8594-42061b6af9cd](https://github.com/user-attachments/assets/2aafb271-bd8d-4080-b045-3fb689a7f36f)

**Comment by BlvckBytes** [comment]
I'm not completely sure on what you mean - is it the fact that you could complete multiple materials in a row? If so, that's intended behavior; you're not just completing materials, but can choose from all predicates, including logical junctions - `and` will be used implicitly. Also note how not all suggestions are meant as tab-completions, especially when using the `?`-syllable to construct custom groups - then, it's meant as a preview of members.

Hopefully I did not completely misunderstand your point - please feel free to elaborate further if that's the case.

**Comment by YuanYuanOwO** [comment]
ohh
okay,got it
