### ISSUE TITLE
Requires specific privileges to execute commands

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/QuickShopSearch#4]
For example, the permission `qss.findshop` is required to execute the command /qss

**Comment by BlvckBytes** [comment]
Please check out the latest release in which I have added quite a few permissions! :) While the config-file will extend itself, I'd advise you to delete it, in order to have the fully updated experience, as we're still within testing-phase.

**Comment by YuanYuanOwO** [comment]
It looks like everything is working! I do have a suggestion for changing the info though

You lack the permission → You don't have the permission

This should help to understand

**Comment by BlvckBytes** [comment]
You're right - simplifying the language will make the plugin more accessible. I've changed it to your suggestion in the latest commit; it'll be within the next release! :)
