### ISSUE TITLE
Add a reload command

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/QuickShopSearch#5]
like:`/qss reload`  
A lib that might be of use:https://github.com/Ghost-chu/SimpleReloadLib

**Comment by BlvckBytes** [comment]
It's a bit hard for me to understand what exactly that library is doing... Do you just intend to reload the configuration-file? Or should the whole `.jar`-file be reloaded? The former would be easily doable with my config-mapper, without any additional libraries. The second option seems a bit dangerous to me, ^^".

**Comment by YuanYuanOwO** [comment]
Just thought might use it. 
reload the configuration-file  
To reload the entire jar file, I can use PlugMan

**Comment by BlvckBytes** [comment]
Exactly, I also thought about `PlugMan`. I'm going to implement reloading here first, and if you're happy with it, I'm going to copy the idea over to the parser.

**Comment by BlvckBytes** [comment]
Please check the [latest release](https://github.com/BlvckBytes/QuickShopSearch/releases/tag/v0.0.7). You should now be able to reload the configuration-file at will; note that this command also affects all currently open GUIs in real time, and can be dispatched from the console or in-game.

**Comment by YuanYuanOwO** [comment]
Works fine for me.

**Comment by BlvckBytes** [comment]
Great! I will go about adding the same functionality to the parser too, alongside another little feature, and notify you in the corresponding issue once things are ready to be tested too.
